name: Run SSHX Command

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sshx-command:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SSHX Command
        run: |
          curl -sSf https://sshx.io/get | sh -s run
